export const ADD_USER = "ADD_USER";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOGOUT_USER = "LOGIN_USER";
export const LOGOUT_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGIN_USER_FAILURE";

export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";

export const FETCH_FEATURED_MOVIES = "FETCH_FEATURED_MOVIES";
export const FETCH_FEATURED_MOVIES_SUCCESS = "FETCH_FEATURED_MOVIES_SUCCESS";
export const FETCH_FEATURED_MOVIES_FAILURE = "FETCH_FEATURED_MOVIES_FAILURE";

export const SET_USER = "SET_USER";
